import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';
import { ReactNode } from 'react';

import './styles/globals.css';
import { auth } from '@/auth';
import { ModalProvider } from '@/app/providers/modal-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang='en'>
        <body className={inter.className}>
          <main
            style={{
              backgroundImage: 'url("/bg-image.jpg")',
              backgroundSize: 'cover',
              backgroundRepeat: 'no-repeat',
              backgroundPosition: 'center',
            }}
            className='w-screen h-screen flex'>
            <ModalProvider />
            {children}
          </main>
        </body>
      </html>
    </SessionProvider>
  );
}
